import 'package:flutter/material.dart';

class Expense {
  // This id will probably be generated by a backend in future
  final String id = UniqueKey().hashCode.toString();

  final String? emoji;
  final String user;
  final String title;
  final double amount;
  final String currency;

  Expense(this.user, this.title, this.amount,
      {this.emoji, this.currency = "€"});
}
