class Expense {
  // This id will probably be generated by a backend in future
  late final String id;

  final String? emoji;
  final String user;
  final String title;
  final double amount;
  final String currency;

  Expense(this.id, this.user, this.title, this.amount,
      {this.emoji, this.currency = "€"});
}
