class Group {
  // This id will probably be generated by a backend in future
  late final String id;

  final String groupName;
  final String owner;
  final double expenses;

  Group(this.groupName, this.owner, this.expenses);
}
