class Group {
  // This id will probably be generated by a backend in future
  late final String id;

  String name;
  String? description;
  String owner;
  List<String> members;

  Group(this.id, this.name, this.description, this.owner, this.members);

  factory Group.fromAppwriteDocument(Map<String, dynamic> data) {
    List<dynamic> membersData = data["members"];
    List<String> members = membersData.cast<String>();

    return Group(data["\$id"], data["groupName"], data["description"],
        data["owner"], members);
  }

  Map<String, dynamic> toDataMap() {
    return {
      "groupName": name,
      "owner": owner,
      "description": description,
      "members": members,
    };
  }
}
