import 'package:flutter/material.dart';
import 'package:splitcount/core/models/group.dart';

class TransactionCategory {
  final IconData icon;
  final String name;
  final String? value;

  TransactionCategory(this.name, this.value, this.icon);
}

final defaultTransactionCategory =
    TransactionCategory("Default", null, Icons.paid_rounded);

final List<TransactionCategory> transactionCategories = [
  defaultTransactionCategory,
  TransactionCategory("Shopping", "shopping", Icons.shopping_cart_rounded),
  TransactionCategory("Gift", "gift", Icons.redeem_rounded),
  TransactionCategory("Sport", "sport", Icons.fitness_center_rounded),
  TransactionCategory("Home", "home", Icons.house_rounded),
  TransactionCategory(
      "Entertainment", "entertainment", Icons.sports_esports_rounded),
  TransactionCategory(
      "Transportation", "transportation", Icons.directions_car_rounded),
  TransactionCategory("Food", "food", Icons.restaurant_rounded),
  TransactionCategory("Ticket", "ticket", Icons.local_activity_rounded),
];

class Transaction {
  // This id will probably be generated by a backend in future
  late final String id;

  late TransactionCategory category;
  final String user;
  final List<String> users;
  final String title;
  final double amount;
  final String currency;
  final DateTime dateTime;
  final Group group;

  Transaction(this.id, this.user, this.users, this.title, this.amount,
      this.dateTime, this.group, this.category,
      {this.currency = "€"});

  factory Transaction.fromAppwriteDocument(Map<String, dynamic> data) {
    var group = Group.fromAppwriteDocument(data["group"]);
    List<dynamic> usersData = data["users"];
    List<String> users = usersData.cast<String>();

    var categoryName = data.containsKey('category')
        ? data['category']
        : defaultTransactionCategory.value;

    var category = transactionCategories.firstWhere(
        (c) => c.value == categoryName,
        orElse: () => defaultTransactionCategory);

    return Transaction(
        data["\$id"],
        data["user"],
        users,
        data["title"],
        (data["amount"] as num).toDouble(),
        DateTime.parse(data["date"] as String),
        group,
        category);
  }
}
