name: Flutter Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "12.x"

      # Setup the flutter environment.
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get

      # Statically analyze the Dart code for and formatting issues.
      - run: dart analyze --fatal-warnings .
      - run: dart format --set-exit-if-changed .

      # Fix tests and enable this here
      # - run: flutter test

      # Flutter build for supported platforms
      - run: flutter build web --no-tree-shake-icons
      - run: flutter build apk --no-tree-shake-icons

      # Upload generated apk to the artifacts.
      - uses: actions/upload-artifact@v3
        with:
          name: splitcount-android
          path: build/app/outputs/apk/release/app-release.apk

      - uses: actions/upload-artifact@v3
        with:
          name: splitcount-web
          path: build/web/
  build-ios-and-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      # Setup the flutter environment.
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get

      # Flutter build for ios and macos
      - run: flutter build ios --no-tree-shake-icons --no-codesign
      - run: mkdir build/ios/iphoneos/Payload && cp -r build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload && zip -r Payload.ipa build/ios/iphoneos/Payload
      - run: flutter build macos --no-tree-shake-icons

      - uses: actions/upload-artifact@v3
        with:
          name: splitcount-ios
          path: build/ios/iphoneos/Runner.app

      - uses: actions/upload-artifact@v3
        with:
            name: splitcount-ios-ipa
            path: build/ios/iphoneos/Payload.ipa

      - uses: actions/upload-artifact@v3
        with:
          name: splitcount-macos
          path: build/macos/Build/Products/Release/Splitcount.app
