name: Flutter Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"

      # Setup the flutter environment.
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter format --set-exit-if-changed .

      # Statically analyze the Dart code for and formatting issues.
      - run: dart analyze --fatal-warnings .
      - run: dart format --set-exit-if-changed .

      # Fix tests and enable this here
      # - run: flutter test

      # Flutter build for supported platforms
      - run: flutter build apk
      - run: flutter build web

      # Upload generated apk to the artifacts.
      - uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
          
      - uses: actions/upload-artifact@v3
        with:
          name: release-web
          path: build/web/
